# Generated by Django 5.2.17 on 2026-08-31 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture', models.CharField(choices=[('efficientnet_b0', 'EfficientNet-B0'), ('resnet50', 'ResNet-50'), ('mobilenet_v3', 'MobileNetV3')], default='efficientnet_b0', max_length=40)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Needs attention')], default='ready', max_length=20)),
                ('accuracy', models.FloatField(default=0)),
                ('macro_f1', models.FloatField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_runs', to='datasets.dataset')),
            ],
        ),
    ]
